let data=[], sort={key:"title",dir:1};
const $=id=>document.getElementById(id);
const fields=["platform","language","type","status","compilable","playable","exact","ai"];
const arr=v=>Array.isArray(v)?v:(v?[v]:[]);
const txt=v=>arr(v).join(", ");
const tri=v=>v===true?"Yes":v===false?"No":"Unknown";
const flag=v=>{const x=tri(v);return '<span class="flag '+x.toLowerCase()+'">'+(x==="Unknown"?"?":x)+'</span>'};
const tags=v=>'<span class="tags">'+arr(v).map(x=>'<span class="tag">'+esc(x)+'</span>').join("")+'</span>';
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function value(r,k){const b=r.build||{},a=r.ai||{};return {title:r.title,source:txt(r.source_platforms),target:txt(r.target_platforms),language:txt(r.reconstructed_languages),type:txt(r.types),started:r.re_started,updated:r.last_activity,compilable:tri(b.compilable),playable:tri(b.playable),exact:tri(b.byte_exact),ai:tri(a.usage)}[k]??""}
function unique(key){return [...new Set(data.flatMap(r=>arr(r[key])).filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function populate(){for(const [id,key] of [["platform","source_platforms"],["language","reconstructed_languages"],["type","types"],["status","status"]]){for(const v of unique(key)){const o=document.createElement("option");o.value=o.textContent=v;$(id).append(o)}}}
function matches(r){const q=$("q").value.trim().toLowerCase(),b=r.build||{},a=r.ai||{};
 const hay=[r.title,r.notes,...arr(r.tags),...arr(r.techniques),...arr(r.source_platforms),...arr(r.target_platforms),...arr(r.reconstructed_languages)].join(" ").toLowerCase();
 return (!q||hay.includes(q))&&(!$("platform").value||arr(r.source_platforms).includes($("platform").value))&&(!$("language").value||arr(r.reconstructed_languages).includes($("language").value))&&(!$("type").value||arr(r.types).includes($("type").value))&&(!$("status").value||r.status===$("status").value)&&(!$("compilable").value||tri(b.compilable)===$("compilable").value)&&(!$("playable").value||tri(b.playable)===$("playable").value)&&(!$("exact").value||tri(b.byte_exact)===$("exact").value)&&(!$("ai").value||tri(a.usage)===$("ai").value)}
function render(){const rs=data.filter(matches).sort((a,b)=>String(value(a,sort.key)??"").localeCompare(String(value(b,sort.key)??""),undefined,{numeric:true})*sort.dir);$("count").textContent=rs.length;$("sortnote").textContent="— sorted by "+sort.key+(sort.dir<0?" ↓":" ↑");
 $("rows").innerHTML=rs.map(r=>{const b=r.build||{},a=r.ai||{};return '<tr data-id="'+esc(r.id)+'"><td><strong>'+esc(r.title)+'</strong></td><td>'+tags(r.source_platforms)+'</td><td>'+tags(r.target_platforms)+'</td><td>'+tags(r.reconstructed_languages)+'</td><td>'+tags(r.types)+'</td><td>'+esc(r.re_started??"?")+'</td><td>'+esc(r.last_activity??"?")+'</td><td>'+flag(b.compilable)+'</td><td>'+flag(b.playable)+'</td><td>'+flag(b.byte_exact)+'</td><td>'+flag(a.usage)+'</td></tr>'}).join("");
 document.querySelectorAll("#rows tr").forEach(tr=>tr.onclick=()=>details(data.find(r=>r.id===tr.dataset.id)))}
function details(r){const b=r.build||{},a=r.ai||{};const line=(k,v)=>'<dt>'+k+'</dt><dd>'+v+'</dd>';$("detailbody").innerHTML='<h2>'+esc(r.title)+'</h2><dl class="details-grid">'+line("Repository",r.repo?'<a href="'+esc(r.repo)+'">'+esc(r.repo)+'</a>':"?")+line("Source platform",tags(r.source_platforms))+line("Target platform",tags(r.target_platforms))+line("CPU",tags(r.source_cpu))+line("Languages",tags(r.reconstructed_languages))+line("Types",tags(r.types))+line("Started",esc(r.re_started??"?"))+line("Last activity",esc(r.last_activity??"?"))+line("Last checked",esc(r.last_checked??"?"))+line("Compilable",tri(b.compilable))+line("Runnable",tri(b.runnable))+line("Playable",tri(b.playable))+line("Byte exact",tri(b.byte_exact))+line("AI usage",tri(a.usage))+line("AI tools",tags(a.tools))+line("Techniques",tags(r.techniques))+line("Tags",tags(r.tags))+line("Notes",esc(r.notes||""))+'</dl>';$("details").showModal()}
fetch("web/projects.json").then(r=>r.json()).then(x=>{data=x;populate();render()}).catch(e=>{$("rows").innerHTML='<tr><td colspan="11">Could not load project data: '+esc(e)+'</td></tr>'});
$("q").oninput=render;fields.forEach(x=>$(x).onchange=render);$("clear").onclick=()=>{$("q").value="";fields.forEach(x=>$(x).value="");render()};document.querySelectorAll("th[data-key]").forEach(th=>th.onclick=()=>{sort=sort.key===th.dataset.key?{key:sort.key,dir:-sort.dir}:{key:th.dataset.key,dir:1};render()});document.querySelector("#details .close").onclick=()=>$("details").close();